name: Import Game Deals

on:
  workflow_dispatch: {}

jobs:
  import-deals:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./scheduler/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./scheduler

      - name: Run script
        run: node index.js
        working-directory: ./scheduler
        env:
          SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}